#--------------------------------------
# Menus Settings
# identifier : Unique ID cannot be repeated
# name       : Menu name
# pageref    : Link of webiste and not appeare same time with url
# url        : Exteneral link out of website and start with http or https
# pre        : Icon of menu
# weight     : Order number and smaller is top
# -------------------------------------
main:
  - identifier: home
    name: home
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: about
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: archives
    name: archives
    pageref: /archives
    pre: archive
    weight: 4
  - identifier: commonweal
    name: 404
    url: /404.html
    pre: heartbeat
    weight: 5
